### ISSUE TITLE
`carts` service health endpoint fails after some time of running

### ISSUE THREAD

**Issue by pgressa** [pgressa/oraclecloud-cloudnative#24]
```
 ERROR i.m.m.health.indicator.HealthResult - Health indicator [oracle.ucp.jdbc.PoolDataSourceImpl@758862e0] reported exception: java.sql.SQLException: Connection was not valid
java.sql.SQLException: Connection was not valid
	at io.micronaut.management.health.indicator.jdbc.JdbcIndicator.lambda$getResult$0(JdbcIndicator.java:99)
	at io.micronaut.core.async.publisher.AsyncSingleResultPublisher$ExecutorServiceSubscription.lambda$request$1(AsyncSingleResultPublisher.java:100)
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedRunnable.run(InvocationInstrumenterWrappedRunnable.java:47)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:79)
	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:157)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by graemerocher** [comment]
Root cause

```
java.lang.ClassCastException: class oracle.ucp.UniversalConnectionPoolException cannot be cast to class java.sql.SQLException (oracle.ucp.UniversalConnectionPoolException is in unnamed module of loader 'app'; java.sql.SQLException is in module java.sql of loader 'platform')
	at oracle.ucp.common.Service.create(Service.java:845)
	at oracle.ucp.common.Service.create(Service.java:606)
	at oracle.ucp.common.Topology.create(Topology.java:151)
	at oracle.ucp.common.Core.growBorrowed(Core.java:1252)
	at oracle.ucp.common.UniversalConnectionPoolImpl.helpGrowBorrowed(UniversalConnectionPoolImpl.java:393)
	at oracle.ucp.common.UniversalConnectionPoolImpl.borrowConnectionWithoutCountingRequests(UniversalConnectionPoolImpl.java:339)
	at oracle.ucp.common.UniversalConnectionPoolImpl.borrowConnectionAndValidateHelper(UniversalConnectionPoolImpl.java:196)
	at oracle.ucp.common.UniversalConnectionPoolImpl.borrowConnectionAndValidate(UniversalConnectionPoolImpl.java:156)
	at oracle.ucp.common.UniversalConnectionPoolImpl.borrowConnection(UniversalConnectionPoolImpl.java:129)
	at oracle.ucp.jdbc.JDBCConnectionPool.borrowConnection(JDBCConnectionPool.java:175)
	at oracle.ucp.jdbc.oracle.OracleJDBCConnectionPool.borrowConnection(OracleJDBCConnectionPool.java:601)
	at oracle.ucp.jdbc.oracle.OracleConnectionConnectionPool.borrowConnection(OracleConnectionConnectionPool.java:109)
	at oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:1839)
```

**Comment by graemerocher** [comment]
Full stack

```
Caused by: java.lang.ClassCastException: class oracle.ucp.UniversalConnectionPoolException cannot be cast to class java.sql.SQLException (oracle.ucp.UniversalConnectionPoolException is in unnamed module of loader 'app'; java.sql.SQLException is in module java.sql of loader 'platform')
	at oracle.ucp.common.Service.create(Service.java:845)
	at oracle.ucp.common.Service.create(Service.java:606)
	at oracle.ucp.common.Topology.create(Topology.java:151)
	at oracle.ucp.common.Core.growBorrowed(Core.java:1252)
	... 25 common frames omitted
oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection (CONNECTION_ID=UyHYPTvvRHiunCmeMAQMNA==)
	at oracle.ucp.util.UCPErrorHandler.newUniversalConnectionPoolException(UCPErrorHandler.java:369)
	at oracle.ucp.util.UCPErrorHandler.throwUniversalConnectionPoolException(UCPErrorHandler.java:59)
	at oracle.ucp.util.UCPErrorHandler.throwUniversalConnectionPoolException(UCPErrorHandler.java:82)
	at oracle.ucp.jdbc.oracle.OracleDriverConnectionFactoryAdapter.createConnection(OracleDriverConnectionFactoryAdapter.java:116)
	at oracle.ucp.common.Database.createPooledConnection(Database.java:283)
	at oracle.ucp.common.Service$2.exec(Service.java:662)
	at oracle.ucp.common.Service$2.exec(Service.java:659)
	at oracle.ucp.actors.InterruptableActor.doAction(InterruptableActor.java:128)
	at oracle.ucp.common.Service.createConnectionInterruptably(Service.java:659)
	at oracle.ucp.common.Service.create(Service.java:837)
	at oracle.ucp.common.Service.create(Service.java:606)
	at oracle.ucp.common.Topology.create(Topology.java:151)
	at oracle.ucp.common.Core.growBorrowed(Core.java:1252)
	at oracle.ucp.common.UniversalConnectionPoolImpl.helpGrowBorrowed(UniversalConnectionPoolImpl.java:393)
	at oracle.ucp.common.UniversalConnectionPoolImpl.borrowConnectionWithoutCountingRequests(UniversalConnectionPoolImpl.java:339)
	at oracle.ucp.common.UniversalConnectionPoolImpl.borrowConnectionAndValidateHelper(UniversalConnectionPoolImpl.java:196)
	at oracle.ucp.common.UniversalConnectionPoolImpl.borrowConnectionAndValidate(UniversalConnectionPoolImpl.java:156)
	at oracle.ucp.common.UniversalConnectionPoolImpl.borrowConnection(UniversalConnectionPoolImpl.java:129)
	at oracle.ucp.jdbc.JDBCConnectionPool.borrowConnection(JDBCConnectionPool.java:175)
	at oracle.ucp.jdbc.oracle.OracleJDBCConnectionPool.borrowConnection(OracleJDBCConnectionPool.java:601)
	at oracle.ucp.jdbc.oracle.OracleConnectionConnectionPool.borrowConnection(OracleConnectionConnectionPool.java:109)
	at oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:1839)
	at oracle.ucp.jdbc.PoolDataSourceImpl.access$300(PoolDataSourceImpl.java:220)
	at oracle.ucp.jdbc.PoolDataSourceImpl$3.build(PoolDataSourceImpl.java:3976)
	at oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:1784)
	at oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:1739)
	at oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:1725)
	at io.micronaut.management.health.indicator.jdbc.JdbcIndicator.lambda$getResult$0(JdbcIndicator.java:91)
	at io.micronaut.core.async.publisher.AsyncSingleResultPublisher$ExecutorServiceSubscription.lambda$request$1(AsyncSingleResultPublisher.java:100)
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedRunnable.run(InvocationInstrumenterWrappedRunnable.java:47)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:79)
	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:157)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection (CONNECTION_ID=UyHYPTvvRHiunCmeMAQMNA==)
	at oracle.ucp.util.UCPErrorHandler.newUniversalConnectionPoolException(UCPErrorHandler.java:369)
	at oracle.ucp.util.UCPErrorHandler.throwUniversalConnectionPoolException(UCPErrorHandler.java:59)
	at oracle.ucp.util.UCPErrorHandler.throwUniversalConnectionPoolException(UCPErrorHandler.java:82)
	at oracle.ucp.jdbc.DriverConnectionFactoryAdapter.createConnection(DriverConnectionFactoryAdapter.java:129)
	at oracle.ucp.jdbc.oracle.OracleDriverConnectionFactoryAdapter.createConnection(OracleDriverConnectionFactoryAdapter.java:84)
	... 34 more
Caused by: java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection (CONNECTION_ID=UyHYPTvvRHiunCmeMAQMNA==)
	at oracle.jdbc.driver.T4CConnection.handleLogonNetException(T4CConnection.java:874)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:679)
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:1069)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:90)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:681)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:602)
	at oracle.ucp.jdbc.DriverConnectionFactoryAdapter.createConnection(DriverConnectionFactoryAdapter.java:123)
	... 35 more
Caused by: oracle.net.ns.NetException: The Network Adapter could not establish the connection (CONNECTION_ID=UyHYPTvvRHiunCmeMAQMNA==)
	at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:594)
	at oracle.net.resolver.AddrResolution.resolveAndExecute(AddrResolution.java:565)
	at oracle.net.ns.NSProtocol.establishConnection(NSProtocol.java:937)
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:346)
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:2147)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:644)
	... 40 more
Caused by: java.io.IOException: Connection refused, socket connect lapse 0 ms. 0:0:0:0:0:0:0:1 1521  0 (1/1) true
	at oracle.net.nt.TcpNTAdapter.establishSocket(TcpNTAdapter.java:421)
	at oracle.net.nt.TcpNTAdapter.doLocalDNSLookupConnect(TcpNTAdapter.java:303)
	at oracle.net.nt.TcpNTAdapter.connect(TcpNTAdapter.java:265)
	at oracle.net.nt.ConnOption.connect(ConnOption.java:229)
	at oracle.net.nt.ConnStrategy.executeConnOption(ConnStrategy.java:814)
	at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:555)
	... 45 more
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:576)
	at java.base/sun.nio.ch.Net.connect(Net.java:583)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:851)
	at java.base/java.nio.channels.SocketChannel.open(SocketChannel.java:285)
	at oracle.net.nt.TimeoutSocketChannel.connect(TimeoutSocketChannel.java:184)
	at oracle.net.nt.TimeoutSocketChannel.<init>(TimeoutSocketChannel.java:158)
	at oracle.net.nt.TcpNTAdapter.establishSocket(TcpNTAdapter.java:380)
	... 50 more
```

**Comment by graemerocher** [comment]
@pgressa do you have the full stack trace from k8s?

**Comment by pgressa** [comment]
@graemerocher I do not have. But after the upgrade to micronaut 2.5.4 it holds:
```
mushop-carts-7fb5b5fb6f-82fw2         1/1     Running     0          3d9h
```

**Comment by pgressa** [comment]
I'm closing this, not an issue anymore..
